name: Fetch and Release Lists

on:
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday at 00:00 UTC
  workflow_dispatch:       # Also allows manual trigger

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Needed for creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go program to fetch and generate output
        run: |
          go run main.go  -geosite-urls "https://github.com/jameszeroX/zkeen-domains/releases/latest/download/zkeen.dat" -geoip-urls "https://github.com/jameszeroX/zkeen-ip/releases/latest/download/zkeenip.dat" -out output

      - name: Create unique tag from timestamp and commit hash
        id: uniq
        run: |
          echo "id=lists-$(date -u +%Y.%m.%d)" >> $GITHUB_OUTPUT

      # - name: Create GitHub release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ steps.uniq.outputs.id }}
      #     name: Lists ${{ steps.uniq.outputs.id }}
      #     body: |
      #       Auto-generated release on ${{ steps.uniq.outputs.id }}.
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .list files as release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.uniq.outputs.id }}
          files: output/*.list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
